### PR TITLE
cleanup Gemfile, add development dependencies to gemspec.

### PR DESCRIPTION
**Pull request by morgoth**
More on why Gemfile.lock should not be included in version control system: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

### CODE REVIEW

**Comment by romanblick** [comment]
You are right with the Gemfile.lock, but why did you remove vcr and webmock from Gemfile?

**Comment by morgoth** [comment]
I moved them to `gemspec` since tests wont run without them, however rest of gems in Gemfile is optional

**Comment by morgoth** [comment]
ah, one line is missint - updating

**Comment by morgoth** [comment]
Added missing `gemspec` line in Gemfile.
Also added bundler tasks for releasing gem

**Pull request merged**
